title: Wasssupp
subtitle: Happy to help
inputTextFieldHint: Type your message...
initPayload: /get_started
hideWhenNotConnected: true
showFullScreenButton: true
displayUnreadCount: true
customData:
  language: en
mainColor: '#ca4e95'
conversationBackgroundColor: '#ffffff'
userBackgroundColor: '#e8e9fd'
userTextColor: '#6562d7'
assistTextColor: '#070707'
openLauncherImage: >-
  https://www.artofliving.org/sites/www.artofliving.org/files/images/logo/AOL_logo_no_line.png
assistBackgoundColor: '#f2bbb9'
closeImage: >-
  https://www.artofliving.org/sites/www.artofliving.org/files/images/logo/AOL_logo_no_line.png
